version: '3.8'

env_file:
  - .env
services:
  api:
    build: .
    container_name: distance_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NOMINATIM_BASE_URL=${NOMINATIM_BASE_URL}
      - NOMINATIM_USER_AGENT=${NOMINATIM_USER_AGENT}
      - API_V1_STR=${API_V1_STR}
      - PROJECT_NAME=${PROJECT_NAME}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # 不再 depends_on db，启动顺序你自己控制就行
    networks:
      - proxy-net
    volumes:
      - ./logs:/app/logs

networks:
  proxy-net:
    external: true
